name: GithubPages

on:
  push:
    branches: [ main ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - name: Download repo
      uses: actions/checkout@v2

    - name: Install node
      uses: actions/setup-node@v2
      with:
        node-version: '14'

    - name: Set github name
      run: |
        git config --local user.email "ramon@ramonmedeiros.dev"
        git config --local user.name "Ramon Medeiros"
        git remote set-url origin https://${{ secrets.TOKEN }}@github.com/ramonmedeiros/healthinsights.git

    - name: Deploy
      run: |
        npm install
        npm run deploy